import { Code, Layers, Database, Cloud, Shield, Cpu } from "lucide-react";

export const skillGroups = [
    {
        title: "Programming Languages",
        icon: Code,
        items: [
            "Python",
            "JavaScript",
            "TypeScript",
            "Java",
            "C++",
            "C",
            "Go",
            "Solidity",
            "SQL",
            "PHP",
            "Shell Scripting",
            "HTML/CSS",
        ],
    },
    {
        title: "Frameworks & Libraries",
        icon: Layers,
        items: [
            "React.js",
            "Next.js",
            "Node.js",
            "Spring Boot",
            "TailwindCSS",
            "Pandas",
            "NumPy",
            "Scikit-learn",
        ],
    },
    {
        title: "Cloud & DevOps",
        icon: Cloud,
        items: [
            "Google Cloud",
            "AWS",
            "Docker",
            "Kubernetes",
            "Git",
            "GitHub",
            "Jenkins",
            "CI/CD Pipelines",
            "REST APIs",
            "FastAPI",
            "Microservices",
            "WebSockets",
            "NATS",
            "Kafka",
            "Postman",
            "CloudFront",
        ],
    },
    {
        title: "Databases",
        icon: Database,
        items: ["MySQL", "MongoDB", "PostgreSQL", "DynamoDB", "Convex", "SQL Server"],
    },
    {
        title: "AI & Machine Learning",
        icon: Cpu,
        items: [
            "TensorFlow",
            "Vertex AI",
            "OpenAI APIs",
            "Gemini APIs (Live, Lyria, Veo, Nano Banana)",
            "ResNet",
            "YOLO",
            "NLP",
            "Sentiment Analysis",
            "MLOps",
            "Model Versioning",
            "Model Interpretability (LIME)",
            "Data Visualization",
        ],
    },
    {
        title: "Concepts & Tools",
        icon: Shield,
        items: [
            "Data Structures & Algorithms",
            "System Design",
            "OOP",
            "Database Management Systems",
            "Networking",
            "Operating Systems",
            "Application Security",
            "Agile/Scrum",
            "Figma",
            "Jira",
            "Google Workspace",
            "Microsoft Office Suite",
        ],
    },
];
